id: products
type: PageSiderMenu
properties:
  title: Products

actions:
  onEnter:
    - id: fetch_brands  # Fetch the brands_selector lookup request when we enter the page
                        # This will ensure that we have all the new addest brands at all times
      type: Fetch
      params: brands_selector

requests:
  - id: products_table
    type: MongoDBAggregation # MongoDb Aggregation to get the table data
    connectionId: products # Id of the connection defined in the lowdefy.yaml file
    properties:
      pipeline:
        - $sort:
            name: 1 # Sort alphabetically according to the name
  - id: brands_selector # MongoDb Aggregation to get a list of the brands and their _ids to be used by a brand dropdown selector
    type: MongoDBAggregation
    connectionId: brands
    properties:
      pipeline:
        - $project: # Project the correct fields that the dropdown selector expects: a list of value-label pairs
            _id: 0
            label: $name # This is what the user will see in the dropdown
            value: $_id # This is the value of the option selected in the dropdown
        - $sort:
            label: 1 # Sort the list alphabetically according to the label

mutations:
  - id: insert_product
    type: MongoDBInsertOne # MongoDb insertOne mutation to write a new product into the collection
    connectionId: products
    properties:
      doc:
        _state: new_product # Insert the entire new_product object, which contains the product name and description
  - id: update_product
    type: MongoDBUpdateOne # MongoDb updateOne mutation to update the selected product
    connectionId: products
    properties:
      filter:
        _id:
          _state: edit_product._id # Filter the document that matches the selected document's _id (which is nested in the edit_product object)
      update:
        $set:
          _state: edit_product # Update all the fields in the edit_product object, which contains the product name and description
  - id: delete_product
    type: MongoDBDeleteOne # MongoDb deleteOne mutation to delete the selected product's document from the collection
    connectionId: products
    properties:
      filter:
        _id:
          _state: edit_product._id # Filter the document that matches the selected document's _id

  # We created a new_product object and an edit_product object that both contain the product info.
  # The reason for placing the product info field in two separate objects instead of the root 
  # level of state is to make the mutation operations easier and to enable us to have two 
  # separate set of fields that capture the same information.

blocks:
  - id: product_title # Create a Title block
    type: Title
    layout:
      grow: true # Set the block the left side of the page
    properties:
      content: Products # The title's text
  - id: new_product # Create a Button block for adding a new product
    type: Button
    layout:
      shrink: true # Set the block the right side of the page
    properties:
      title: New Product
      icon: PlusOutlined
      hideActionLoading: true # Hides the loading icon when the button is clicked
    actions:
      onClick: # A list of actions to complete when the button is clicked
        - id: reset_product_info # Resets the fields in the new_product object
          type: SetState
          params:
            new_product:
              name: null
              description: null
              brand_id: null
        - id: open_new_drawer # Open the drawer which contains the input fields to add a new product
          type: CallMethod
          params:
            blockId: new_product_drawer # The block id of the drawer
            method: toggleOpen # The method that opens the drawer

  - id: product_list # An agGrid table that lists all the products
    type: AgGrid
    properties:
      defaultColDef: # Define default column definitions that apply to all the defined columns
        sortable: true # Enables sorting on the columns when the header is clicked
        resizable: true # Enables resizing of column widths
        filter: true # Enables filtering of the columns using agGrid's default filter
      rowData:
        _request: products_table # Populate the table with our request that looks up the products
      columnDefs: # Define all the columns
        - headerName: Name # Display name
          field: name # The field name in the data
          width: 200
        - headerName: Description
          field: description
          width: 800
    actions:
      onRowClick: # Define what happens when a row is clicked
        - id: set_edit_product
          type: SetState
          params:
            edit_product: 
              _id:
                _args: row._id # Access the row _args (the row data) to set the _id field in the edit_product object equal the _id field of the selected row
              name:
                _args: row.name
              description:
                _args: row.description
              brand_id:
                _args: row.brand_id
        - id: open_edit_drawer # Open the drawer which contains the input fields to edit the selected product
          type: CallMethod
          params:
            blockId: edit_product_drawer
            method: toggleOpen

  - id: new_product_drawer
    type: Drawer
    properties:
      title: New Product
      width: 512px # Set the width of the drawer to be 512px
    layout:
      contentGutter: 16 # Set a gutter of 16px between all the blocks in the drawer
    blocks:
      - id: new_product.name # Create a single line text box block to capture the new product name
        type: TextInput
        properties:
          title: Name
          placeholder: Product Name # Text to display inside the input box when nothing has been entered yet
      - id: new_product.brand_id # A dropdown selector to select the brand_id of the brand to which this product belongs to
        type: Selector
        properties:
          title: Brand
          placeholder: Select brand
          options:
            _request: brands_selector # Populate the options of the dropdown using the request we defined earlier
      - id: new_product.description
        type: TextArea # A multiline text box block to capture the new product description
        properties:
          title: Description
          placeholder: Product Description
      - id: insert_product
        type: Button
        properties:
          title: Save
          icon: SaveOutlined
          block: true # Makes the button fill the maximum defined width instead of only the with of its contents (title and icon)
        actions:
          onClick:
            - id: insert_product # Call the insert_product mutation
              type: Mutate
              params: insert_product
            - id: fetch_products_table # Fetch the products_table request again to show the newly created product in the table
              type: Fetch
              params: products_table
            - id: close_new_drawer # Close the new_product drawer
              type: CallMethod
              params:
                blockId: new_product_drawer
                method: setOpen  # The method that closes the drawer - set the open state of the drawer to false
                args:
                  open: false

  - id: edit_product_drawer
    type: Drawer
    properties:
      title: New Product
      width: 512px
    layout:
      contentGutter: 16
    blocks:
      - id: edit_product.name
        type: TextInput
        properties:
          title: Name
          placeholder: Product Name
      - id: edit_product.brand_id # A dropdown selector to select the brand_id of the brand to which this product belongs to
        type: Selector
        properties:
          title: Brand
          placeholder: Select brand
          options:
            _request: brands_selector # Populate the options of the dropdown using the request we defined earlier
      - id: edit_product.description
        type: TextArea
        properties:
          title: Description
          placeholder: Product Description
      - id: update_product
        type: Button
        layout:
          span: 12 # Make the button span 2 half of the drawer's width
        properties:
          title: Save
          icon: SaveOutlined
          block: true
        actions:
          onClick:
            - id: update_product
              type: Mutate
              params: update_product
            - id: fetch_products_table
              type: Fetch
              params: products_table
            - id: close_drawer
              type: CallMethod
              params:
                blockId: edit_product_drawer
                method: setOpen
                args:
                  open: false
      - id: delete_product # Button for deleting the product
        type: Button
        layout:
          span: 12
        properties:
          title: Delete
          icon: DeleteOutlined
          type: danger # Set the type of button to a danger button (which is red in color)
          block: true
        actions:
          onClick:
            - id: open_delete_modal # Open a pop up modal to confirm whether you want to delete the product
              type: CallMethod
              params:
                blockId: delete_modal
                method: open
      - id: delete_modal
        type: ConfirmModal
        properties:
          content: Are you sure you want to delete this product? # The text inside the modal
          okText: Yes # Change the default text of the ok button to 'Yes'
          okButton:
            type: danger # Change the default type of the ok button to danger
          cancelText: No # Change the default text of the cancel button to 'No'
        actions:
          onOk:
            - id: delete_product
              type: Mutate
              params: delete_product
            - id: fetch_products_table # Fetch the products_table request again to the list of products without the newly deleted one
              type: Fetch
              params: products_table
            - id: close_edit_drawer
              type: CallMethod
              params:
                blockId: edit_product_drawer
                method: setOpen
                args:
                  open: false
